sudo: required
services:
  - docker

before_install:
  - docker build -t bebofit/docker-react-simple-app -f Dockerfile.dev .

script:
  - docker run -e CI=true bebofit/docker-react-simple-app npm run test

language: generic 
